# Site settings
title: Personal and professional | by Jesse Williams
description: "A simple blog comprised of complex ideas"
url: "https://jwilliamsr.github.io/new-blog/"
author:
  name: "Jesse Williams"
  email: "jessewilliams.r@gmail.com"
  url: "https://jwilliamsr.github.io/new-blog/"

# Build settings
baseurl: /new-blog # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate

# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
