# Site settings
title: A Developer Marketing Blog by Jesse Williams
email: email@example.com
description: "A simple blog focused on the complexity of developer marketing, developer relations, building open source communities, and how to take developer focused products to market."
baseurl: "jwilliamsr.github.io/new-blog/" # the subpath of your site, e.g. /blog
url: "http://jwilliamsr.github.io/new-blog" # the base hostname & protocol for your site
author:
  name: "Jesse Williams"
  email: "jessewilliams.r@gmail.com"
  url: "https://jwilliamsr.github.io/new-blog/"
logo: /img/jesse-williams-logo.png

markdown: kramdown
theme: minima

# Social media settings
twitter_username: FriendsCallMeJW
github_username:  jwilliamsr

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title:output_ext

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

