# Site settings
title: A developer marketing blog by Jesse Williams
description: "A simple blog focused on the complexity of developer marketing"
url: "http://www.jesse-williams.com"
author:
  name: "Jesse Williams"
  email: "jessewilliams.r@gmail.com"
  url: "https://www.jesse-williams.com"

# Build settings
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate

# Custom variables
version: "1.1.2"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
